export const gestureMap = {
        '0': '比心A',
        '1': '比心B',
        '2': '比心C',
        '3':'比心D',
        '4':'OK',
        '5':'手张开',
        '6':'点赞',
        '7':'差评',
        '8':'摇滚',
        '9':'合十',
        '10':'手心向上',
        '11':'握拳',
        '12':'胜利',
        '13':'大V',
        '14':'打电话',
        '15':'作揖',
        '16':'感谢',
        '17':'三',
        '18':'四',
        '19':'手枪',
        '20':'摇滚2',
        '21':'捧脸',
        '22':'敬礼',
        '23':'祈祷',
        '24':'双指比枪',
        '25':'无'
}

export const choice2char = {
        '0': "pos1",
        "1": "pos2",
        "2": "pos3",
}

export const allgesture_zh = [
            '比心A',
            '比心B',
            '比心C',
            '比心D',
            'OK',
            '手张开',
            '点赞',
            '差评',
            '摇滚',
            '合十',
            '手心向上',
            '握拳',
            '胜利',
            '大V',
            '打电话',
            '作揖',
            '感谢',
            '三',
            '四',
            '手枪',
            '摇滚2',
            '捧脸',
            '敬礼',
            '祈祷',
            '双指比枪',
            '无',  // 无,用于单手势设置
]

export const gesture_zh_to_en = {
    '比心A':"heart_a",
    '比心B':"heart_b",
    '比心C':"heart_c",
    '比心D':"heart_d",
    'OK':"ok",
    '手张开':"hand_open",
    '点赞':"thumb_up",
    '差评':"thumb_down",
    '摇滚':"rock",
    '合十':"namaste",
    '手心向上':"palm_up",
    '握拳':"fist",
    '胜利':"victory",
    '大V':"bid_v",
    '打电话':"phonecall",
    '作揖':"beg",
    '感谢':"thanks",
    '三':"three",
    '四':"four",
    '手枪':"pistol",
    '摇滚2':"rock2",
    '捧脸':"holdface",
    '敬礼':"salute",
    '祈祷':"pray",
    '双指比枪':"pistol2",
    '无':"none",
}

export const gesture_en_to_ezh = {
    "heart_a":'比心A',
    "heart_b":'比心B',
    "heart_c":'比心C',
    "heart_d":'比心D',
    "ok":'OK',
    "hand_open":'手张开',
    "thumb_up":'点赞',
    "thumb_down":'差评',
    "rock":'摇滚',
    "namaste":'合十',
    "palm_up":'手心向上',
    "fist":'握拳',
    "victory":'胜利',
    "bid_v":'大V',
    "phonecall":'打电话',
    "beg":'作揖',
    "thanks":'感谢',
    "three":'三',
    "four":'四',
    "pistol":'手枪',
    "rock2":'摇滚2',
    "holdface":'捧脸',
    "salute":'敬礼',
    "pray":'祈祷',
    "pistol2":'双指比枪',
    "none":'无',
}